---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    password: AgByHDyfpvWqEZn4Ym0fftPzlzYr8/rUiaspJd7k0BSen919Hkr+UROaJrtfrvSWhjqGT64tFqNrbPBjOIbAZhvos94XCnSjz1K0bVSp5QtBQIHgRrer9SRXW8vOo4hsjRUDrNCHhKQEACPXzD4B/DVlqyvuWxNiEJS0AMfKuhPIosmMgJDSOK+MjiRO5ED7yzRh9kT0Irb7MOqLRGTr9Ub6jBbg1enK+/hSnBYK0gPDutKNA3WGZKCNOm0OgmsZQj5Dc5+xWuplAkSmt7VkdBwMxgycUEZEo6m6gEKJ+3k40Zhqd4A++WVG8Ujhg54FQmUXGPhG7FrxHm0D0gUFEFq4CS0W5F5uO1fUwFQO2LA+sqbQyxRPBhkk5LcDsAJgvIf3CaMGknCQ1BOz0iR9FXQOH6Mh9KORKpm6V3119PaH03HsTz+HPiYBHEK6EytfJBEKGp6ZSwhSP97QribjOB6Xk+OlhqSFpoP6ldWVyLlXdyej0xrC5K2izQodcYifC/1bx+2bmjpMCye+IbP1vKq4JuQj2TFKaMxQp/6cVrS4gr0VZt+Ez1NN4MJuKhKAWP6CDm4u2Yk2OgmeCGoUF5k3WNHfW7injxTn7jHBYYehfDhTeSuXwd1oXy2LCVh9iFZhu43zP92vjb+SmfF5YS5gazcCJ+f8YDlmS2MctfoSradDmKe+tX59001HKCtpoRg/8d8LpaYz7c11E1okaqHH
    username: AgB06LxfZNj0P+m942YHiyvVU8bk4tTRwqTH/7V93vu9LCL5kHb3ItsYIP8KZ5V0CC+g/s41b5becaBlZ8MCOtGch3cZVHto6u3KJ1oKZ9h3NPh3YJb6aJUPcFe2YQyOdvkagcPk8HfUQJ5A9lei58uHN0A/JVdv4LZ0fGfrw5OCN6mKcdDHSSKw0qtCp+ESqzKzqtP4bHH83huC4YIG21Z1y4j1mw0D9o8bCLlox/Rs3Sb4Dqgfe8MHzm4dUePS1ItqGePSC3VhY9TtFcVLqvppBUXLWcva06DX2GS4oHGJkwwUsDAm6pNFRKDJS208SOTEtT/jYtukgRlUtzy4+DP2V07bbkMoxpGsKC0H1KNZ7nvY6kxhhG3+/wis0xvWhnOzMl//ultsD5B0FRcMpmqEE05EBA8gi14MOAfLz2mmQqfdvHjjLVUvsttVlzOBmb2DMD1xeA3OBMu/W3Ixtq1T6icPew6a6hwnxukEbjz5zfShXfRGuotShb3jq9MupYKAFRzNTMK7qO3+PhCDMDJ8iM1Q3HnEvYr10gobQ1R1yWByGwlqzZF/S27EWKEnj9QESIUyKdQ1/RAlbE2iFT5slHwhrGlsTd+rq/W9e+mLC1WVKXYuCEzeTjUSLR7aRDpOq+VJUTkCU0HDiIHRyATPXoIt+M5Tdxc9qGRjDvG1CLiua/C3ajdskGJOD6WzbU5EuWRpsSosP8U=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud
    type: Opaque
