apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
   replicas: 1
   image: postgres:16-alpine
   database:
      size: 2Gi
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: nextcloud-db-secret
              key: password

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: nextcloud-db-secret
              key: replication-password
