apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: nextcloud
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`cloud.trivernis.net`, `nextcloud.trivernis.dev`)
    kind: Rule
    middlewares:
      - name: strict-security-headers
        namespace: default
    services:
    - name: nextcloud
      port: http
