apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-secret
  namespace: forgejo
spec:
  encryptedData:
    database: AgDbUHZcALsdkIMHs6wTdKpUzma4ugEuGxeV2zIwhqsMrEyMk0Ud6f020/Hdr2zB+kz1Zj+zot7hItSEcIHS9Olxbqyr3drBii4n9+kMHB/cMQ4CBSuGSaylqI66I8zDWtLxRESi6JKcwH/p1/4VyYiVA9oqzqklki0UZGucB2flEAKRbTfuxHmXxCo8JQYGEMBBpYaIjVsGEgJ6QyWGJkUKaopSyZtCInf//D/Nt8X38HU1UQVrlXbeKwnnExk9Zg80hNV0uFZaBNPfaSSn8fiLU9ck4aZf+s2qJX3uYemvZuaieOcrX89gVcYsN9zbk9ADSLbak7eeuSwFdzK1rteEqHdHcNC3L8N7ssemRX9gCKUEuE/gmW7YdfbevjyUlArAcEillrCatZ92IXZFr5YQL2rhLraCUI7Pq58Qrza3Yz7/+8bhVvAl8ocTUggua6qwPpEbxDW7w4f/j8VpJMeLQ9Y/L1ASHmw+71tdGwuWsif42gqOUW0kS/nZwiLDae1xY3p+gRv9oN0zCZYhX8+MuRq4zPrj9zYoq2+5Iee2390jm55/qPd6K3nmmOGjR93Up5Y37jWP0Is9mLIX0xjvrym9DwUQFDLQZy5iIYRBmoTR4jJxhQp4BDiWZwAIUvW2gPWcujiQCwAQcXRf239xL/Lpcolh/eSNUp7zsdCJ4Xq5NSi4p7S2dAd2zg1Z5hC6NItTnNoWh/MpR3dvPAX3a3SzZ1JtLNuwjYyd+EPlRpwhIK4YXFcW1RwPilH3+euzD6O8o8FkOGuw5I2a9RMSEURmk5wUQkeUqBotIFTYzIcTLJk26DivYlnA2NBOK7ZXpZ8=
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-secret
      namespace: forgejo
    type: Opaque

