apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: searxng
  namespace: searxng
spec:
  releaseName: searxng
  chart:
    spec:
      chart: searxng
      sourceRef:
        kind: HelmRepository
        name: searxng
        namespace: repos
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    env:
      INSTANCE_NAME: trivial      
      BASE_URL: https://search.trivernis.net

    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 2Gi

    controller:
      replicas: 2

    redis:
      enabled: true
      resources:
        requests:
          memory: 64Mi
        limits:
          memory: 128Mi
    searxng:
      config:
        use_default_settings: true
        general:
          # Debug mode, only for development. Is overwritten by ${SEARXNG_DEBUG}
          debug: false
          # displayed name
          instance_name: "trivial"
          # For example: https://example.com/privacy
          privacypolicy_url: false
          # use true to use your own donation page written in searx/info/en/donate.md
          # use false to disable the donation link
          donation_url: false
          # mailto:contact@example.com
          contact_url: false
          # record stats
          enable_metrics: true

        search:
          # Filter results. 0: None, 1: Moderate, 2: Strict
          safe_search: 0
          # Existing autocomplete backends: "dbpedia", "duckduckgo", "google", "yandex",
          # "seznam", "startpage", "swisscows", "qwant", "wikipedia" - leave blank to turn it off
          # by default.
          autocomplete: "qwant"
          # minimun characters to type before autocompleter starts
          autocomplete_min: 4
          # Default search language - leave blank to detect from browser information or
          # use codes from 'languages.py'
          default_lang: "all"

          formats:
            - html
            - json
            - rss

        server:
          limiter: false  # rate limit the number of request on the instance, block some bots

          secret_key: "5adbd8a47c2523a1d3b2db02197bd8ac222b36827e1b89d9315be262082bf258"  # Is overwritten by ${SEARXNG_SECRET}
          # Proxying image results through searx
          image_proxy: false
          # 1.0 and 1.1 are supported
          method: "POST"
          default_http_headers:
            X-Content-Type-Options: nosniff
            X-XSS-Protection: 1; mode=block
            X-Download-Options: noopen
            X-Robots-Tag: noindex, nofollow
            Referrer-Policy: no-referrer

        ui:
         # query_in_title: When true, the result page's titles contains the query
          # it decreases the privacy, since the browser can records the page titles.
          query_in_title: false
          # infinite_scroll: When true, automatically loads the next page when scrolling to bottom of the current page.
          infinite_scroll: false
          # ui theme
          default_theme: simple
          # center the results ?
          center_alignment: false
          # URL prefix of the internet archive, don't forgett trailing slash (if needed).
          # cache_url: "https://webcache.googleusercontent.com/search?q=cache:"
          # Default interface locale - leave blank to detect from browser information or
          # use codes from the 'locales' config section
          default_locale: ""
          # Open result links in a new tab by default
          # results_on_new_tab: false
          theme_args:
            # style of simple theme: auto, light, dark
            simple_style: auto

        # Lock arbitrary settings on the preferences page.  To find the ID of the user
        # setting you want to lock, check the ID of the form on the page "preferences".
        #
        # preferences:
        #   lock:
        #     - language
        #     - autocomplete
        #     - method
        #     - query_in_title

        # Comment or un-comment plugin to activate / deactivate by default.
        #
        enabled_plugins:
        #   # these plugins are enabled if nothing is configured ..
        #   - 'Hash plugin'
        #   - 'Search on category select'
          - 'Self Information'
          - 'Tracker URL remover'
          - 'Ahmia blacklist'  # activation depends on outgoing.using_tor_proxy
        #   # these plugins are disabled if nothing is configured ..
          - 'Hostname replace'  # see hostname_replace configuration below
          - 'Open Access DOI rewrite'
          - 'Vim-like hotkeys'
          - 'Tor check plugin'
        #   # Read the docs before activate: auto-detection of the language could be #   # detrimental to users expectations / users can activate the plugin in the
        #   # preferences if they want.
        #   - 'Autodetect search language'

        # Configuration of the "Hostname replace" plugin:
        #
        hostname_replace:
          # '(.*\.)?youtube\.com$': 'invidious.example.com'
          # '(.*\.)?youtu\.be$': 'invidious.example.com'
          # '(.*\.)?youtube-noocookie\.com$': 'yotter.example.com'
          # '(.*\.)?reddit\.com$': 'teddit.net'
          # '(.*\.)?redd\.it$': 'teddit.net'
          '(www\.)?twitter\.com$': 'nitter.woodland.cafe'
          # to remove matching host names from result list, set value to false
          # 'spam\.example\.com': false
          '(.*\.)?g2\.com$': false
          'alternativeto\.net$': false
          'easycodeforall\.com$': false
          'slant\.co$': false
          'stackshare\.io$': false
          'bleepcoder\.com$': false
          'githubja\.com$': false
          'gitmemory\.com$': false
          'giters\.com$': false
          'githubmemory\.com$': false
          'githubmate\.com$': false
          'wenyanet\.com$': false
          'issueexplorer\.com$': false
          'opensourcelibs\.com$': false
          'awesomeopensource\.com$': false
          'findbestopensource\.com$': false
          'githubhelp\.com$': false
          'golangrepo\.com$': false
          'gitmemory\.cn$': false
          'pythonissues\.com$': false
          'reposhub\.com$': false
          'openprojectrepo\.com$': false
          'gitanswer\.com$': false
          'githubplus\.com$': false
          'pythonrepo\.com$': false
          'bestofcpp\.com$': false
          'github\.innominds$': false
          'higithub\.com$': false
          'githublab\.com$': false
          'githubhot\.com$': false
          'issuehint\.com$': false
          'kotaeta\.com$': false
          'code\.i$': false
          '(.*\.)?qastack\.(jp|ru|it|mx|com|info|in|fr|cn|co|kr|vn|net|id)$': false
          'coder\.work$': false
          'webdevqa\.jp$': false
          'codeflow\.site$': false
          'codeguides\.site$': false
          'overcoder\.net$': false
          'coderoad\.ru$': false
          'javaer101\.com$': false
          'voidcc\.com$': false
          'siwib\.org$': false
          'fluffyfables\.com$': false
          'fixes\.pub$': false
          'knews\.vip$': false
          'isolution\.pro$': false
          'uwenku\.com$': false
          'zsharp\.org$': false
          'projectbackpack\.org$': false
          'waymanamechurch\.org$': false
          'sunflowercreations\.org$': false
          'cfadnc\.org$': false
          'fitforlearning\.org$': false
          'panaindustrial\.com$': false
          'sierrasummit2005\.org$': false
          'theshuggahpies\.com$': false
          'pcbconline\.org$': false
          'nuomiphp\.com$': false
          'ubuntu\.buildwebhost$': false
          'ubuntuaa\.com$': false
          'debugcn\.com$': false
          'sch22\.org$': false
          'gupgallery\.com$': false
          'amuddycup\.com$': false
          'ecnf2016\.org$': false
          'softwareuser\.asklobster$': false
          'domainelespailles\.net$': false
          'pakostnici\.com$': false
          'try2explore\.com$': false
          'itectec\.com$': false
          'stackovergo\.com$': false
          'faithcov\.org$': false
          'noblenaz\.org$': false
          'culinarydegree\.info$': false
          'qapicks\.com$': false
          'narkive\.jp$': false
          'ourladylakes\.org$': false
          'intellipaat\.com$': false
          'newbedev\.com$': false
          'codenong\.com$': false
          'routinepanic\.com$': false
          'tousu\.in$': false
          'tutorialmore\.com$': false
          'titanwolf\.org$': false
          'coderedirect\.com$': false
          'fullstackuser\.com$': false
          'ostack\.cn$': false
          'wujigu\.com$': false
          'webdevdesigner\.com$': false
          'ghcc\.net$': false
          'developreference\.com$': false
          'semicolonworld\.com$': false
          'tipsfordev\.com$': false
          'xsprogram\.com$': false
          'stackoom\.com$': false
          'cndgn\.com$': false
          'generacodice\.com$': false
          'stackfinder\.jp$': false
          'sqlite\.in$': false
          'stackguides\.com$': false
          'younggeeks\.in$': false
          'answerlib\.com$': false
          'edupro\.id$': false
          'stackfinder\.ru$': false
          'jscodetips\.com$': false
          '5axxw\.com$': false
          'codefaq\.info$': false
          'codefaq\.ru$': false
          'mediatagtw\.com$': false
          'progi\.pro$': false
          'elfishgene\.com$': false
          'sysadminde\.com$': false
          'answacode\.com$': false
          'jablogs\.com$': false
          'jpdebug\.com$': false
          'askcodez\.com$': false
          'iquestion\.pro$': false
          'ntcdoon\.org$': false
          'programmierfrage\.com$': false
          'microeducate\.tech$': false
          'debugko\.com$': false
          'devdreamz\.com$': false
          'catwolf\.org$': false
          '1r1g\.com$': false
          'string\.quest$': false
          'reddit\.fun$': false
          'qa\.icopy$': false
          'errorsfixing\.com$': false
          'syntaxfix\.com$': false
          'codegrepr\.com$': false
          'quabr\.com$': false
          'serveanswer\.com$': false
          'safehavenpetrescue\.org$': false
          'cainiaojiaocheng\.com$': false
          'linuxfixes\.com$': false
          'flutterhq\.com$': false
          'dailydevsblog\.com$': false
          '711web\.com$': false
          'binarydevelop\.com$': false
          'so\.muouseo$': false
          'peaku\.co$': false
          'learnfk\.com$': false
          'solveforum\.com$': false
          'edureka\.co$': false
          'itecnote\.com$': false
          'tagsqa\.com$': false
          'faqcode4u\.com$': false
          'digitrain\.ru$': false
          'prograide\.com$': false
          'dovov\.com$': false
          'oomake\.com$': false
          'ajaxhispano\.com$': false
          'codebaoku\.com$': false
          'daplus\.net$': false
          'questu\.ru$': false
          'itranslater\.com$': false
          'doraprojects\.net$': false
          'iteramos\.com$': false
          'faqcodes\.com$': false
          'mejorcodigo\.com$': false
          'anycodings\.com$': false
          'javafixing\.com$': false
          'xstack\.us$': false
          'shenghuobao\.net$': false
          'overstack\.in$': false
          'zaizhele\.cn$': false
          'zaizhele\.net$': false
          'xstack\.ru$': false
          'mlink\.in$': false
          'jonic\.cn$': false
          'jike\.in$': false
          '16892\.net$': false
          'vigges\.net$': false
          '55276\.net$': false
          'ogeek\.cn$': false
          'shenzhenjia\.net$': false
          'shenzhenjia\.cn$': false
          '9ishenzhen\.com$': false
          'vigge\.net$': false
          'vigge\.cn$': false
          'yaoply\.com$': false
          'techhelpnotes\.com$': false
          'querythreads\.com$': false
          'appsloveworld\.com$': false
          'dtuto\.com$': false
          'qatop\.pythonwood$': false
          'webdevask\.com$': false
          'laravelquestions\.com$': false
          'py4u\.net$': false
          'article\.docway$': false
          'xiu2\.net$': false
          'codehero\.jp$': false
          'quabr\.com$': false
          'webdevqa\.jp$': false
          'exceptionshub\.com$': false
          'pythonwd\.com$': false
          'alwaysemmyhope\.com$': false
          'pretagteam\.com$': false
          'easysavecode\.com$': false
          'stackqna\.com$': false
          'imtqy\.com$': false
          'christfever\.in$': false
          'codersatellite\.com$': false
          'coredump\.biz$': false
          'farath\.com$': false
          'devbugfix\.com$': false
          'tech\.wayne$': false
          'stackify\.dev$': false
          'webknox\.com$': false
          'jpndev\.com$': false
          'stackfault\.net$': false
          'howtofix\.io$': false
          'buzzphp\.com$': false
          'askdev\.vn$': false
          'quares\.ru$': false
          'examplefiles\.net$': false
          'codewdw\.com$': false
          'jpcodeqa\.com$': false
          'tutorialguruji\.com$': false

        categories_as_tabs:
          general:
          images:
          videos:
          news:
          map:
          music:
          it:
          science:
          # files:
          social media:

        engines:
        ### Modified engines
          - name: wikipedia
            weight: 2

          - name: presearch
            disabled: false
            weight: 1.2

          - name: wiby
            disabled: false

          - name: stract
            engine: stract
            shortcut: str
            disabled: false
          
        ### Custom Engines ###

          - name: safebooru
            shortcut: sboo
            engine: xpath
            categories: [boards]
            paging: true
            page_size: 40
            search_url: https://safebooru.org/index.php?page=post&s=list&tags={query}&pid={pageno}
            results_xpath: //div/span[@class='thumb']/a
            url_xpath: ./@href
            title_xpath: ./@id
            content_xpath: ./img/@title
            thumbnail_xpath: ./img/@src
            disabled: true
            timeout: 5.0
            tokens: ['12boards24access!']
            about:
              website: https://safebooru.org
              use_official_api: false
              results: HTML
              language: en

          - name: danbooru
            shortcut: dboo
            engine: xpath
            categories: [boards]
            paging: true
            search_url: https://danbooru.donmai.us/posts?tags={query}&page={pageno}
            results_xpath: //div/article
            url_xpath: ./div/a/@href
            title_xpath: ./@id
            content_xpath: ./div/a/picture/img/@title
            thumbnail_xpath: .//img/@src
            disabled: true
            timeout: 5.0
            tokens: ['12boards24access!']
            about:
              website: https://danbooru.donmai.us
              use_official_api: false
              results: HTML
              language: en
