apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sharkey
metadata:
  name: sharkey
resources:
  - app/namespace.yaml
  - app/sealedsecret.yaml
  - app/config-sealedsecret.yaml
  - app/config.yaml
  - app/volume.yaml
  - app/stackgres-scripts.yaml
  - app/stackgres-pooling.yaml
  - app/stackgres.yaml
  - app/deploy.yaml
  - app/service.yaml
  - app/route.yaml
