apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stackgres
  namespace: stackgres
spec:
  releaseName: stackgres-operator
  chart:
    spec:
      chart: stackgres-operator
      sourceRef:
        kind: HelmRepository
        name: stackgres
        namespace: repos
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    authentication:
      secretRef:
        name: stackgres-secret
    cert:
      createForOperator: true
      createForWebApi: false
      secretName: stackgres-secret
      certManager:
        autoConfigure: true
    deploy:
      restapi: false
      operator: true
