apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-ssd
  namespace: openebs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: hostpath
      - name: BasePath
        value: /var/clusterstore
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
    - cluster-server-1
    - cluster-server-2
    - cluster-dedicated-1
