apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: longhorn-secret
  namespace: longhorn-system
spec:
  encryptedData:
    users: AgAO6N9pDyXrnWR7Ukpnh6EXE9DSu3Z1SH6nJMkbNOLNp8a2LBog7A/3LxETDfEhjQBbO+MsqzU38c2FxmcorVQN8oo3yXRFx921UVH7JcwbZdmgMtTPaucGUN0FhhpIXj+6hzT3JJcCiy8SAalG9cFWVQKjXesR4cpJ6JleVKGm7iownstCuCfHFSTCp6ef3YKAkXP8cVPDkcxXXWXyMfIkK13Rhol7U/exzSRktBseuxIKOIpkuzjEqb9/TCkHuE+jlWN+ObBvolk74p6wMDHcK9vG7gwJRYU0CzsgdWZsxTx/T7VaO1We+qF+6dJxyFrvt3aUpR7h3lF4kTEFZ6DTiGyjpNvQQH2A3Ci6pJw0vkmWMq35nhipQIN1FzM7D3YwmwkzZYREYqrn9d6ojC3yOWJ8PncqGYAik067u/BTCAu5rLLvJITs2dAsB8prkHbseBST2AbdC7MEzrEjssrPu7dj/OBRUCfN1qYx31tP5zsXohJhNJ4jKVT2ILgoC64PsRQgiHnMdzerttRNx30j64qFNN57NY5TtaxsFNVENWZ7UGPPouyh1Qs0nkFnrdWoQy8hN1uKvXDmk5TK1wUSlD1iSrR/ihno/B7zbmI7rS9TjH9FH4xSDHelIGY3Q86ln7cl72iQzU9DyHFk36SGmtSIt/ZduEa4ZKnc3WIgW/i1CzUyQnLdqT9M24i72Zq42EKFAH4kMZOUednnj1gLpHq7Dr3TEEDuEtVv0BFVJui1IRD32icFgmw789SisP55
  template:
    metadata:
      creationTimestamp: null
      name: longhorn-secret
      namespace: longhorn-system

