apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  releaseName: uptime-kuma
  chart:
    spec:
      chart: uptime-kuma
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
