apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  releaseName: uptime-kuma
  chart:
    spec:
      chart: uptime-kuma
      sourceRef:
        kind: HelmRepository
        name: irsigler
        namespace: repos
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    volume:
      storageClassName: ebs-ssd
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 512Mi
      
