apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: uptime-kuma
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`status.cluster.trivernis.dev`, `status.cluster.trivernis.net`, `status.trivernis.dev`, `status.trivernis.net`)
    kind: Rule
    middlewares:
      - name: strict-security-headers
        namespace: default
    services:
    - name: uptime-kuma
      port: http 
