---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uptime-kuma-secret
  namespace: uptime-kuma
spec:
  encryptedData:
    values: AgBPxx0Q0RzNfiTBYDwFF4wNlxrZoFT7sA1N3l777fVvfjbicb3sYeXLNxXKl0rsQ8Mo4ZVGxvfQGfMVw2hqiGjTVeFbUEE/ehZA2CbhseUUfRflp505J8gDsCttT+7u3vRYSpjzRD656U27YJwv+UQjTUBU6f63eQyCRAbqzKZ302HlvuFo11xv7n5g4KZ847j5S+/WKKtpgpaO8xOz2HGgROWmDIXcaizweXAOqG78mjrXiZiQLi+yTEZxnjmcpor+VfSAUEJJ1p4zirgPwTVgWlu6+bqiO92JU3cFj6RHg/OO4oKLizEILyxoV1hMRj8EOK+6OytBYnc4ya8DD9IM0+Vb1PTje2HxM6Q1dh3j8U6VZjdBL7KykePSxZ0bpS4MV0eRAoksLyHnF25fDpb/OnRlHmIDQq7ttVcGRh3FMsHfVxaCDJ/xweJmfo/0YRLe1EbLkauHe1BhP0gduPyrv/1kgQ5td2E/e4vBXsDL09LFeog2UZ1RCIzjIvXUFTNEtjDIMlYrTvZN5CG0Mnyej8/uZRkArVmeISFisy5J76UkRbIQAcdiRvrneaYWfkjJif+JTq0mY+kl1GFYuf5TYgun0PoxDjyaemjpf8OeOaCQFUVRAA3f+Pz7I7hHAMtfH9GsQTLs6ml5Rlv+Fy5xC3v9KEXH0hgGS7cJXgEo8DRvSQ9FNoO/Um0rtObuPPnOV+atFv/buOK1PcxRn1l67X3bWWKRZRREsWf5EJEZDuixAqJX97luDy6Swd6oMDg+H/3DkM498Bd2JfwBEyN4hRU0C22BRglKrySEgNfIdvEL+BdhRS32t5cXT9SGCEthYCIynXYQ8AUHI57dFK3U
  template:
    metadata:
      creationTimestamp: null
      name: uptime-kuma-secret
      namespace: uptime-kuma
    type: Opaque
