---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    root-password: AgArMf9XnZpJsu7rr+5vZR00X9prgSuxDQzc+lYowmi6yvqv2ADAK4QqKwWQktPrnd23F+Aohs7x4SVricnxfD7j0Tq+8z3JBA/emFZpbJr19Rrb2nOm+Rs95Fuy/cbkOSuupbIllAn4/t1uHK7xxJTC8jB+HFcWWVhq/dbDEK4GiiX0tlGrv+XhELRq8Ox1vRWnxOj/CcRc5A+mehNHygJZwFIykB9EBVqMKWFvU6b3BCZI+K9BYlnGkAuVxRUuhBzsYZ1Ka4szYoxsr7WYwJM6jl4Ibn1mm24KoEkEqHG5zlNro/MUR67aVTWRcwtg800NaMV81K744gyzrXjooYQD6ocL1KnA7z6eDhlxyZyzuyq2fO0gWdcYe0dRoDgfGUwfauSSM4jeezZ9sX5dkQZbUAyGT8TEVTC9XC6HhgbJ8bDvBpV2M9xx9bZldJ+xCJ/FID7hmjp4GUXkzAegNxGEhoZymeMR1ow1JUlsDGdqMe+GCOrDxEEUn0gAJ5M0pWQe2PjhNYgmx9qXz5aNE2lgPHS+lLh8ITNgZvtt7Jx48nR8dAPEWsSfa3LClE/sPFLngFL1tgH5h+9IzsbgOLZAc1oZLsd53FkHKoT5yjqR48nhJUAMahAgDVdDgSfF0emQTvjq2RU65J/4d5w1nUuHftrkT9RpcT9/HsxshZBW4l17Z4zCGn6UPyUMyK6L54Fq1QaHBX/MsDxXOMM8Ew==
    root-user: AgBRbmjGPDZD/Uut5+85wac7jGd3detU4e5d1Rv/s1iLYxvWZ7uD0Fb9VWoZFYodeo6/QAzZMAZdxPqUv1f9Sr6eZj+jmkrzBa1D63w48jmDhfUJ/rQ7eXmKnjtdEk5H+2avuSE318XhtebU1oMPujyLdtLj80992FV1FRNADvg1bvVSZsZmYLGVQ8yw3f7+vRMM9uFihQvmYO7Jrt75lCvWP24xz7u8J0ykqf1tIXNJVM6GWVoNULOwortytDoB5UFX7HSod5PpA9dVpt7YNbESbDAQFI8GLYneZuTHN9QkTQPcXW/j4PpC61t8tlmtMKT58/fuVT2svyU3KxPbJUECIZjEjTqWplhgBRLIbXyCGIN5clS2KKPyMpjWETU0Q2j+kJNuo1kM4bXerRfiRD7lhfskWvr2PzIf5JPnfnKUCRGUAvkZ7HHgjpXa/sX5SFp4xijRJeKKMpaHj97hwn+ut+BqklvxNwkUACFElAQE45/9b3LAiaPx181HcuVj2TQmA2RmO/3/saEbaTEhL/kRmZN5tS60Y3BYgq4wMjFM1tlIe/5jOGfN3ZppeZ7e3IJy6O+QBe6Rf4SFIvOnl7qbDYQLX3UV8b6g0j+R1BrIxzbnrn+fJZtb30ZUEN0JBwQvWSwFNGuO4r0zBdtDOTipfpN0rh7m9BtB000j1hGaJ5DpYFn9ZlUM06CO1NisfopC4yFuuIAVXas=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
    type: Opaque
