apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  releaseName: minio
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: repos
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    auth:
      existingSecret: minio-secret
    persistence:
      enabled: true
      storageClass: ebs-hdd
      size: 100Gi
    metrics:
      serviceMonitor:
        enabled: true
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/minio/v2/metrics/cluster"
      prometheus.io/port: "9000"
    extraEnvVars:
      - name: MINIO_BROWSER_REDIRECT_URL
        value: https://minio-ui.trivernis.dev
      - name: MINIO_SERVER_URL
        value: https://minio.trivernis.dev

