apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
metadata:
  name: nextcloud
commonLabels:
  app: nextcloud
resources:
  - app/namespace.yaml
  - app/nextcloud-db-sealedsecret.yaml
  - app/nextcloud-sealedsecret.yaml
  - app/postgres.yaml
  - app/release.yaml
  - app/route.yaml
