apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: default
spec:
  headers:
    stsSeconds: 15768000
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: same-origin
    customFrameOptionsValue: SAMEORIGIN

    customResponseHeaders:
      X-Robots-Tag: noindex,nofollow
      X-Download-Options: noopen
      X-Powered-By: coffee