apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--entryPoints.web.proxyProtocol.trustedIPs=10.0.0.254"
      - "--entryPoints.web.forwardedHeaders.trustedIPs=10.0.0.254"
    ports:
      web:
        exposedPort: 8000
      websecure:
        exposedPort: 8443
      ssh:
        port: 8022
        expose: true
        exposedPort: 8022
        protocol: TCP