apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--providers.kubernetescrd.allowCrossNamespace=true"
    ports:
      web:
        exposedPort: 8000
        forwardedHeaders:
          trustedIPs:
            - "10.0.0.254"
            - "167.235.111.84"
        proxyProtocol:
          trustedIPs:
            - "10.0.0.254"
            - "167.235.111.84"
      websecure:
        exposedPort: 8443
        forwardedHeaders:
          trustedIPs:
            - "10.0.0.254"
            - "167.235.111.84"
        proxyProtocol:
          trustedIPs:
            - "10.0.0.254"
            - "167.235.111.84"
      ssh:
        port: 8022
        expose: true
        exposedPort: 8022
        protocol: TCP

      sct-discovery:
        port: 21027
        expose: true
        exposedPort: 21027
        protocol: UDP

      sct-listen:
        port: 22000
        expose: true
        exposedPort: 22000
        protocol: TCP

      minecraft:
        port: 25565
        expose: true
        exposedPort: 25565
        protocol: TCP

      minecraft-voice:
        port: 24454
        expose: true
        exposedPort: 24454
        protocol: UDP

    metrics:
      prometheus:
        headerLabels:
          useragent: User-Agent
          origin: Origin
          referer: Referer
          forwarded-for: X-Forwarded-For
          forwarded-host: X-Forwarded-Host
          forwarded-proto: X-Forwarded-Proto
        addRoutersLabels: true
        service:
          enabled: true
        serviceMonitor:
          jobLabel: traefik
          interval: 30s

