apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: woodpecker
  namespace: woodpecker
spec:
  releaseName: woodpecker
  chart:
    spec:
      chart: woodpecker
      sourceRef:
        kind: HelmRepository
        name: woodpeckerci
        namespace: repos
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    persistentVolume:
      storageClassName: ebs-ssd
    server:
      env:
        WOODPECKER_HOST: "https://ci.trivernis.dev"
        WOODPECKER_OPEN: true
      resources:
        requests:
          memory: 256Mi
        limits:
          memory: 512Mi
      prometheus:
        podmonitor:
          enabled: true
    agent:
      env:
        WOODPECKER_BACKEND_K8S_STORAGE-CLASS: "ebs-ssd"
        WOODPECKER_BACKEND_K8S_STORAGE_RWX: false
      resources:
        requests:
          memory: 256Mi
          cpu: 1
        limits:
          memory: 512Mi
          cpu: 2

      
