apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-flux
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/flux
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-localstorage
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/localstorage
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-openebs
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/openebs
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-stackgres
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/stackgres
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-forgejo
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/forgejo
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-metrics
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/metrics
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-uptime-kuma
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/uptime-kuma
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-plantwiki
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/plantwiki
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-plantwiki-dev
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/plantwiki-dev
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-searxng
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/searxng
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-tandoor
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/tandoor
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/traefik
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-miniflux
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/miniflux
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-syncthing
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/syncthing
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-nextcloud
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/nextcloud
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-woodpecker
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/woodpecker
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-discordbot-2b
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/discordbot-2b
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-sharkey
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/sharkey
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-minio
  namespace: flux-system
spec:
  dependsOn:
    - name: repos
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/minio
  prune: true
  wait: true
  timeout: 5m0s
