apiVersion: v1
kind: Namespace
metadata:
  name: repos
  labels:
    name: repos
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repos
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./repos
  prune: true
  wait: true
  timeout: 5m0s
