apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
metadata:
  name: flux-webhook
resources:
  - app/webhook-service.yaml
  - app/webhook-route.yaml
  - app/webhook-sealedsecret.yaml
  - app/webhook-receiver.yaml
  - app/weave-sharedsecret.yaml
  - app/weave-release.yaml
  - app/weave-router.yaml
