apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
metadata:
  name: flux-webhook
resources:
  - flux/webhook-service.yaml
  - flux/webhook-route.yaml
  - flux/webhook-sealedsecret.yaml
  - flux/webhook-receiver.yaml
