apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: config-receiver
  namespace: flux-system
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: config-webhook-token
  resources:
    - kind: GitRepository
      name: flux-system