apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
metadata:
  name: uptime-kuma
patches:
  - patch: |-
      - op: replace
        path: spec/values/image/tag
        value: 1.23.7-debian
resources:
  - app/namespace.yaml
  - app/release.yaml
  - app/route.yaml
