apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
metadata:
  name: uptime-kuma
resources:
  - app/namespace.yaml
  - app/release.yaml
  - app/sealedsecret.yaml
  - app/route.yaml
