apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
metadata:
  name: uptime-kuma
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: uptime-kuma
    patch: |-
      - op: add
        path: /spec/values/image/tag
        value: 1.23.7-debian
      - op: add
        path: /spec/chart/spec/version
        value: 1.3.3
resources:
  - app/namespace.yaml
  - app/release.yaml
  - app/route.yaml
