apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-path-storage
metadata:
  name: local-path-storage
resources:
  - app/config.yaml
  - app/deploy.yaml
  - app/hdd-storageclass.yaml
  - app/ssd-storageclass.yaml
