apiVersion: apps/v1
kind: Deployment
metadata:
  name: lychee
  namespace: lychee
  labels:
    app: lychee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lychee
  template:
    metadata:
      labels:
        app: lychee
    spec:
      containers:
      - image: lycheeorg/lychee:v5.1.2
        name: lychee
        volumeMounts:
        - name: lychee-uploads
          mountPath: "/lychee/uploads"
        - name: lychee-config
          mountPath: "/lychee/conf"
        - name: lychee-sym
          mountPath: "/lychee/sym"
        - name: lychee-sqlite
          mountPath: "/lychee/db"
        ports:
          - containerPort: 80
            name: http 
            protocol: TCP    
        env:
        - name: PHP_TZ
          value: Europe/Berlin
        - name: TIMEZONE
          value: Europe/Berlin
        - name: DB_CONNECTION
          value: sqlite
        - name: DB_DATABSE
          value: /lychee/db/lychee.db
        - name: APP_URL
          value: https://lychee.trivernis.net
        - name: APP_FORCE_HTTPS
          value: "true"
      volumes:
      - name: lychee-sym
        persistentVolumeClaim:
          claimName: lychee-sym-pvc
      - name: lychee-sqlite
        persistentVolumeClaim:
          claimName: lychee-sqlite-pvc
      - name: lychee-uploads
        persistentVolumeClaim:
          claimName: lychee-uploads-pvc
      - name: lychee-config
        persistentVolumeClaim:
          claimName: lychee-config-pvc
