apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: lychee
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`lychee.trivernis.net`, `lychee.iulse.com`)
    kind: Rule
    middlewares:
      - name: strict-security-headers
        namespace: default
    services:
    - name: lychee
      port: http 
