apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-uploads-pvc
  namespace: lychee
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-hdd"
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-sym-pvc
  namespace: lychee
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-ssd"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-sqlite-pvc
  namespace: lychee
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-ssd"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-config-pvc
  namespace: lychee
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-ssd"
  resources:
    requests:
      storage: 1Gi
