---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-secret
  namespace: velero
spec:
  encryptedData:
    minio-credentials: AgCdRmoiTEbsD2cNux0Xu4BNASExBbrqhe3DbPpc8xmReIDLot0wyvGd4zBp21dsSskZQrij4K0ZoaYqHT/tq0FQKFaL9G+Z6+lGxXKxTIBf+HnFf35iM1g8Z1K9NIa1QLqr9aOoRHg3PPlmzSYDGNXGmR3fp4UwPFg7TUJOAoMvmV2hzNU9ZeZjfMOcUC+HpXlV8Q8r/u9dugyL4hBO24JTms1R+TF5uX2Kk6kJ7fHGDJpj63CVgjBjtROOlJ/rc2eqKTnKOE2ULZ4UVJZfIAlrxtA8wkXNoFy8hSiF2MzFLCLeFWyJBZZiGinVm56B5h+YaBU0lfj7cv8mKAHJQxomHJsgytbFcMb6debGkbih20w33O59p3JpPWmCKmfZuOPTEh1TK9W9RfH3o+UGlv1DF1EII1y9Q5qIEQOlVKe2Xa/5YH085lUVn+904MSV7spjTeupE2uzhiYuA38x1ZXQsxq46J05thK1Usldsk9y4EMdx0/P0veMtWT68ek2CXep3lKdS16B8JFnTunkDhOto/XECZW2qzgvE2X/Gnx3d1+xSfdZeKzByLbhSFr/Le/dIZEAgTFbltsmDPaxZjNNPmx6Ii+Y2B0sb8vJOp4ePnIkTVJ24WEl5DOkOeBzNfbquDQ4NuFL4Mz9K20+fFdMKYtjkdWTs1uhYRa+RJFrhm/BD/Lg1rCFrAU+39roOLhuIe4opmpm7wI0uizCl1+OB8QB8N7uguPodPFTCtbxLv1MpxNBvOzFL/O9s/dHPDqY22SqIvwOzeIHgmlukh5GJpRk0HzDOeY/e/tHicFDf/f0zkumWj8j2Z3N9R7Tc5pk9/kz1Cv0NQ==
  template:
    metadata:
      creationTimestamp: null
      name: velero-secret
      namespace: velero
    type: Opaque
