---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-secret
  namespace: velero
spec:
  encryptedData:
    cloud: AgAyHSDzvAgvCblsLqnOU1Aw+otVKo41VYJb+8yBoz3tAGkL8JowG7tuk8cLGOH3uaeTvjHrhTz0FSRGJbLeIF9QgPBiTM4Dvs5MRkLtKi+Bkl+5clZvUDVbv6imxz0+jmN6g/u7fTVQ84Nj2xbIiHybbc2Kuy7T6mKIE56Y59akefSdhK2EaOtZTG31g/ZyDPs3JnCLrcGiJlAX4JRJNxr3rE8BYmE9PpZVw5k6j0LpsuAdUwDjFCMN5NtDcIzMS6o/SNRaK7765ROd6AaKsZLVVltXoQl5fHWq0QFuW/KvGQ86i/LmjbQqFu9A39qe81l/6MmdUpMeglvA3ipt1KvLmGneMLf1oM9EHL0rCuAMeZja1re60fM3NTv0g66HZm/C8Oxhx3xs7Xq/JRKzg+xaK2taeuoCbYmCkK4gBWNkkDjQmrODzbAG/pm52XRhLBacc65pG0kpRj82b59xH+waaB6iZLTRJyU/OkoyvLJ3+7Tymp/YFZI/HFurrUS8T/dCVGKSvAacIfvA4UnWpxlLfb5V8SqO3LA/kKaL2Ka3PvfeGYQqfSL4xl48E51tElAN3Ox8swmASsZ5RlEtnB3XmQElMHILCnHwoNeHGHnaB9Pve5II4ZS+MRq/u92V0Wy7OwFdLhVQ1ZNI88LFFPFf+jleRy+nLWfAh0k51DVj/BsYxcGZMeZC/EwhfHnigISplowOIjjuLQzn+RjI4fq5liTWyS2Jpx403I3HxpgMv586BBLOw85wkQ4Bvv4RhPQ1114ylRIvjrGzmSHF0fT9wpAeJ2s3RCmg7ns6kODu1RLcQpX8tKzwmYSqPrhz9lXs73shHTKS5hEeYcjFkK2x
  template:
    metadata:
      creationTimestamp: null
      name: velero-secret
      namespace: velero
    type: Opaque
