apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  releaseName: velero
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: repos
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    metrics:
      serviceMonitor:
        enabled: true
    configuration:
      backupStorageLocation:
      - name: cluster-minio
        provider: aws
        bucket: velero-backup
        default: true
        credential: 
          name: velero-secret
          key: minio-credentials
        config:
          region: minio
          s3ForcePathStyle: "true"
          s3Url: https://minio.trivernis.dev
        
