apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  releaseName: velero
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: repos
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    metrics:
      serviceMonitor:
        enabled: true
    deployNodeAgent: true
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.8.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
    credentials:
      existingSecret: velero-secret 
    configuration:
      volumeSnapshotLocation: []
      backupStorageLocation:
      - name: cluster-minio
        provider: aws
        bucket: velero-backup
        default: true
        credential: 
          name: velero-secret
          key: cloud
        config:
          region: minio
          s3ForcePathStyle: "true"
          s3Url: https://minio.trivernis.dev
        
