apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics
metadata:
  name: metrics
resources:
  - app/namespace.yaml
  - app/metrics-sealedsecret.yaml
  - app/release.yaml
  - app/rbac.yaml
  - app/route.yaml
  - app/monitor.yaml
