---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sharkey-config-secret
  namespace: sharkey
spec:
  encryptedData:
    secret.yml: AgAoRcHn+oEu3mkVOcn1UY38X+ljcudtpV2FKJALWyuC2dZpcd31SZeMz5FD9b4iQQXHsvcqZpkQ710ZfLkX0nomTzhIrA7xQhSyif7N9FGpxCNYbBhoL4J7X3OrLUWcaOqwCaARs0O7fsJrvbMAHC2Y8KdBs3c5hhOlAglHGC6q5nKAypmnYLJJLy4qScD+++meP1y7447+bl9REJvmPIJiaG9nlwvRFgzb/IWUlA9e1XLmF1BJOlNCGunEirysOUzJN2Ro1T+LARBsngJxYb/xNngrvh4W+Gt1foXoYFfrmn2al/HiNBzqoRK0hRgic83LPQjeIOfjtJz1+P34PMHZS97dFrn7LrAD2Kk1D0z/jXXMbmj3oLgi1NPEKyaOthNZZTGWlGq75aOwWBVJEjGATKRZEu2X2j6o1Rul5BQ5luHpcT9tZ4pqqj8lSZvL7lRY3YrVcbDaIKRkvr4y21cs4czu0ViJIGnkSfAgPXMpzZVlFJhKdso1T+GSDwuODjr+xN4YVsboMCKbZGqQw3rMzVx1/jFOmIyiH/cWLBofofEYVCYq8B0PytK3jE0DwaZoz/hN/n3goecU6LhoS4norUDB15C3cbc1hRr32hMFzwvSkMzGK6L3KdIOF5nZupfBv5nNEZPwdOGgRe3h81AlT8k1/PbBDbrTnDACDFvLLC2TCXUVbHN/pUTBxXn3Ol1/akpRfOUAboUh2ZmgHiaRN4JibKkNWtHmU5rmoTqkDytTxtQC1w1/Z7Ybt3mTLKATw45MZo36B4UkOCLvNvtbmzv3oOTr0K7srPTbOwtAnUeJgQ5dDOrb8SWLWJL/OilrpcT5y0uW0RTZvkYQbB31yk1c
  template:
    metadata:
      creationTimestamp: null
      name: sharkey-config-secret
      namespace: sharkey
    type: Opaque
