---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sharkey-config-secret
  namespace: sharkey
spec:
  encryptedData:
    secret.yml: AgAiw2slTXLctPiu0A/Aa7DgHKq60MkzMHhBJtSyu5Jjz2uNf5IG3w8dolA4Fix56vZGTND2ZXeATq3qL9sidkonLCi1iQ6za5rOpMV4jUKQdkMcUvbXKy71RPe3SsBQ7ezpfAEHlulw2LDM93Tb+2DiFB/oi5S9BrHljqNmG2pfvFSiKoXXUi5M8DPoT8rfc+EnKdM2dIs6CmbsPI1c04YXkEjEqBaTW4rHRcDRoBH0GykuTHAa2raGEcIoYGJoeV7Ghd2ZExUtYolZibBBPvAbyVWAseYeghUBJEy/gdLFKicOXKQ7+uC1KAYCmIqQ9gL3o9Bd0sV0qeRS3G8A79XqEkvH8OrBMuseIfSkED1OnIS/Gm7vtJ+lRXwfPBn98eK0akAsDPA2aISznmBlFOjS0WTzTFECS0bkWpEDvPEpFsoL0suGHm0suTZFm5qdCLZOhmjHfWU2Vu1Yc4BBAH+D1a7BMHBQsH4IDuKGNqlSvJRGeB4lsMuecAonnWzc1wZi+K+NllRfqRfG87Tskw2VZmRSnFBcVEFPntF3otNG3IQQ3kc8HsotJkd1ta8n5ScxIHGUbSNCGtiRZ7zdttsU736wf53tgDSK8eZY2ogMDbRz+OZfFxHYqiBEgx2P04UaP/vpJzV2oBfESvA61xmER9+c6VDQzA3utv6FZge26/VfTBEQFwRsX5uZ4M9qoPPklml1cwVvHJVl1I/VATmR1rrK+dMAQGGszRlFDPYDWp1e53NzmcKcTN3cTmvTSbFcO3kQlhU49NQb3+r49X+BwKFULdY2zFOXdKGcBIAEn5oXRIkoHIOMvRrJxu6H9B2yE3tXLrUgFMQ6dZlL/8X4VU6o
  template:
    metadata:
      creationTimestamp: null
      name: sharkey-config-secret
      namespace: sharkey
    type: Opaque
