apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: sharkey
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`sharkey.trivernis.dev`)
    kind: Rule
    middlewares:
      - name: strict-security-headers
        namespace: default
    services:
    - name: sharkey
      port: http 
