apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharkey-files-pvc
  namespace: sharkey
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-hdd"
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharkey-config-pvc
  namespace: sharkey
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-ssd"
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharkey-redis-pvc
  namespace: sharkey
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-ssd"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharkey-meilisearch-pvc
  namespace: sharkey
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-ssd"
  resources:
    requests:
      storage: 1Gi
