apiVersion: v1
kind: PersistentVolume
metadata:
  name: sharkey-files
  namespace: sharkey
spec:
  capacity:
    storage: 10Gi
  storageClassName: "ebs-hdd"
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: sharkey-files-pvc
    namespace: sharkey
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharkey-files-pvc
  namespace: sharkey
spec:
  storageClassName: "ebs-hdd"
  volumeName: sharkey-files
