apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  releaseName: minecraft
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-charts
        namespace: repos
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        memory: 512Mi
    persistence:
      storageClass: ebs-ssd
      dataDir:
        enabled: true
    extraEnv:
      USE_AIKAR_FLAGS: true
    minecraftServer:
      eula: true
      type: FABRIC
      version: 1.20.4
      difficulty: hard
      motd: Welcome to ClusterCraft!
      ops: trivernis
      pvp: true
      forceRedownload: true
      removeOldMods: true
      vanillaTweaksShareCodes: 
        - vYxGa9
        - fN49Us
      rcon:
        enabled: true
        withGeneratedPassword: true
      memory: 4G
      extraPorts:
        - name: voicechat
          containerPort: 24454
          protocol: UDP
          ingress: 
            enabled: false
          service:
            enabled: true
            embedded: true
            port: 24454
        - name: map
          containerPort: 8100
          protocol: TCP
          ingress: 
            enabled: false
          service:
            enabled: true
            embedded: true
            port: 8100
      modrinth:
        projects:
          - fabric-api
          - silk
          - bluemap
          - bmarker
          - chunky
          - chunkyborder
          - carpet
          - carpet-tis-addition
          - fabric-language-kotlin
          - universal-graves
          - ledger
          - lithium
          - starlight
          - spark
          - simple-voice-chat
          - debugify
          - inventory-management

    mcbackup:
      enabled: true
      pruneBackupDays: 1
      persistence:
        storage-class: ebs-hdd
        backupDir:
          enabled: true
          
          
