apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: game
  namespace: minecraft
spec:
  entryPoints:
    - minecraft
  routes:
  - match: HostSNI(`*`)
    services:
    - name: minecraft-minecraft
      port: minecraft
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: voice
  namespace: minecraft
spec:
  entryPoints:
    - minecraft-voice
  routes:
  - match: HostSNI(`*`)
    services:
    - name: minecraft-minecraft
      port: voicechat
