apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: weave-secret
  namespace: flux-system
spec:
  encryptedData:
    values: AgDM+1F89R3FPF7v8saOJsxgxdrdfuBBQX6XYkPjPuRRUQ+OpN2jELnKqbYD+IWcLPDhgXCAHoJVVHY0zslHx8ZX0GqAI1ywzocBJMrBAy1kC1+IhIA/YLdoerpuYLo9AqNYIVVG4VizpCZJnWt1aLPTeceHjPIJ0qpGA1vTGIzVxPbDGD/MO3fWZ8Tt3rYjffupsnW8DvzuNtkp53HWwuYA2UoCr0Ayxzh2J9aTjhjjp9i5x8JPWWM+NLLICHI/HjUWlPbd+Me/9pmtCsz/co6Kvob2zfH7QdneJ6wFxYijon8V3TX6Foe1spBKSgCiABmYzsDx313gvii7NG3KharZAJo45FvxGJk5LNNzg+QB4n/LrEftXYBgFIcLKisHX7KA7ILeq5bKjM0kfFqSad+HPFe62SPhjTt/pGQTmQiRzkGt4L6PHH2oU2PJhtVNqT22T18lfWPWSG+g7lzgx/Y6xXhLCWD//5ooLuy6oOpH4hHUr/AzAZW2oa3cIK+KtizFzN3j5632Wcby3TZhL4/Pkc2E3Bdv4pHlqVVvrcVP+4QquDcCz2qomt00X/A07WoYOasyds9u/svg7t6AlNfXQ2aX9bvjaQ+416OJDeI0M0UriKNnQ85W6L8x7CxMx8vi+vdxtyzb8AVsy0CnkNwxjQ+Ki7Cgm8j88ZQOsnHBLZl5Z6M6aq/gk4tGfywCGw+GpclW28uBqDa9byN3KayltHnq/uADB5CWIsdWNlZ2sB5bXDzBJ8O6WvNvmzhNOvqaekdAFL0DzBssNwqKVwfYZgaAWP+YHHf0UW2QnSWkgRGq2cHxY6WNYyhAbtBSnPW2M4qxxH2H2QSe+AsMCcgvkmSyy0MZOz5W
  template:
    metadata:
      creationTimestamp: null
      name: weave-secret
      namespace: flux-system
    type: Opaque

