apiVersion: v1
kind: Namespace
metadata:
  name: plantwiki
  labels:
    name: plantwiki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantwiki
  namespace: plantwiki
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plantwiki
  template:
    metadata:
      labels:
        app: plantwiki
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: plantwiki
      containers:
      - image: git.trivernis.net/trivernis/plantwiki:latest
        name: plantwiki
        ports:
        - name: port-plantwiki
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: plantwiki-srv
  namespace: plantwiki
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: plantwiki
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: plantwiki-route
  namespace: plantwiki
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`plantwiki.trivernis.dev`)
    kind: Rule
    services:
    - name: plantwiki-srv
      port: 80
  - match: Host(`plantwiki.trivernis.net`)
    kind: Rule
    services:
    - name: plantwiki-srv
      port: 80