apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  namespace: discordbot-2b
  name: cluster
spec:
  postgres:
    version: '16'
  instances: 2
  pods:
    persistentVolume:
      size: '2Gi'
      storageClass: ebs-ssd
  managedSql:
    scripts:
    - sgScript: cluster-scripts
