apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  namespace: discordbot-2b
  name: cluster-scripts
spec:
  scripts:
  - name: init-db
    scriptFrom:
      secretKeyRef:
        name: 2b-secret
        key: init-db.sql
  - name: init-user
    scriptFrom:
      secretKeyRef:
        name: 2b-secret
        key: init-user.sql
