apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: miniflux-db
  namespace: miniflux
spec:
   replicas: 2
   image: postgres:16-alpine
   database:
      size: 2Gi
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: miniflux-secret
              key: postgres-password

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: miniflux-secret
              key: replication-password
