apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: miniflux
  namespace: miniflux
spec:
  releaseName: miniflux
  chart:
    spec:
      chart: miniflux
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: repos
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    postgresql:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: miniflux-secret
      valuesKey: values