apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: syncthing
spec:
  releaseName: syncthing
  chart:
    spec:
      chart: syncthing
      sourceRef:
        kind: HelmRepository
        name: k8s-home-lab
        namespace: repos
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    persistence:
      data:
        enabled: true
        storageClass: ebs-hdd
