apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: syncthing
spec:
  releaseName: syncthing
  chart:
    spec:
      chart: syncthing
      sourceRef:
        kind: HelmRepository
        name: k8s-home-lab
        namespace: repos
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    persistence:
      data:
        enabled: true
        storageClass: ebs-hdd
        accessMode: ReadWriteOnce
        size: 200Gi

    service:
      main:
        ports:
          http:
            port: 8384
      listen:
        enabled: true
        type: NodePort
        externalTrafficPolicy: Local
        ports:
          listen:
            enabled: true
            port: 22000
            protocol: TCP
            targetPort: 32200
            nodePort: 32200
      discovery:
        enabled: true
        type: NodePort
        externalTrafficPolicy: Local
        ports:
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
            targetPort: 30027
            nodePort: 30027
