kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-hdd
provisioner: cluster.local/local-path-provisioner
parameters:
  nodePath: /mnt/data/cluster-local-storage
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
