kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-hdd
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt/data/cluster-local-storage
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
