kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-ssd
provisioner: rancher.io/local-path
parameters:
  nodePath: /var/cluster-local-storage
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
