apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: recipes-route
  namespace: tandoor
spec:
  entryPoints:
    - web
  routes:
  - match: (Host(`recipes.trivernis.dev`) || Host(`recipes.trivernis.net`)) && (Path(`/media`) || Path(`/static`))
    kind: Rule
    services:
    - name: recipes-service
      port: 80
  - match: Host(`recipes.trivernis.dev`) || Host(`recipes.trivernis.net`)
    kind: Rule
    services:
    - name: recipes-service
      port: 8080
