apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: tandoor-headers
  namespace: tandoor
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: recipes-route
  namespace: tandoor
spec:
  entryPoints:
    - web
  routes:
  - match: (Host(`recipes.trivernis.dev`) || Host(`recipes.trivernis.net`)) && (Path(`/media`) || Path(`/static`))
    kind: Rule
    middlewares:
      - name: security-headers
        namespace: default
    services:
    - name: tandoor
      port: 80
  - match: Host(`recipes.trivernis.dev`) || Host(`recipes.trivernis.net`)
    kind: Rule
    middlewares:
      - name: security-headers
        namespace: default
      - name: tandoor-headers
    services:
    - name: tandoor
      port: 8080