apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tandoor
metadata:
  name: tandoor
resources:
  - app/namespace.yaml
  - app/recipes-sealedsecret.yaml
  - app/postgres.yaml
  - app/release.yaml
  - app/route.yaml
