apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tandoor
metadata:
  name: tandoor
resources:
  - app/namespace.yaml
  - app/service-account.yaml
  - app/recipes-sealedsecret.yaml
  - app/config.yaml
  - app/pvc.yaml
  - app/postgres.yaml
  - app/deploy.yaml
  - app/service.yaml
  - app/route.yaml
