apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: recipes-db
  namespace: tandoor
spec:
   replicas: 2
   image: postgres:16-alpine
   database:
      size: 2Gi
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: recipes-secret
              key: postgresql-password

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: recipes-secret
              key: replication-password
