apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-media
  namespace: tandoor
  labels:
    app: recipes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-hdd-crypto-global
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-static
  namespace: tandoor
  labels:
    app: recipes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi