apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: metrics
spec:
  releaseName: prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: repos
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    namespaceOverride: metrics
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 1Gi
    prometheus:
      monitor:
        interval: 10s
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
              spec:
                storageClassName: ebs-ssd
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 5Gi
  valuesFrom:
    - kind: Secret
      name: metrics-secret
      valuesKey: values     

