apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: metrics
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    namespaceOverride: metrics
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessMode: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi

