apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-route
  namespace: metrics
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`grafana.trivernis.dev`) || Host(`grafana.trivernis.net`)
    kind: Rule
    services:
    - name: prometheus-stack-grafana
      port: 80
