apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
metadata:
  name: woodpecker
resources:
  - app/namespace.yaml
  - app/woodpecker-sealedsecret.yaml
  - app/release.yaml
  - app/route.yaml
